name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display Secrets
        run: |
          echo "Displaying environment variables"
        env:
          WORKSPACE: "${{ github.workspace }}"
          MACHINE: "${{ runner.os }}"
          VAULT_USER: "${{secrets.VAULT_USER}}"
          VAULT_KEY: "{{secret.VAULT_KEY}}"
      - name: Print the secrets on the console
        run: |
          echo "Vault Usename: $VAULT_USER"
          echo "Vault Secret key: $VAULT_KEY"
          
